name: remember_me
description: A Polymer Dart application.
dependencies:
  event_bus: any
  polymer: ">=0.10.0-pre.12 <0.11.0"
  polymer_elements: ">=0.2.0-pre.5 <0.3.0"
transformers:
- polymer:
    entry_points: web/index.html
