name: remember_me
version: 0.0.1
description: A Polymer Dart application.

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  polymer: ^1.0.0-rc.12
  web_components: ^0.12.0
  polymer_elements: ^1.0.0-rc.5
  logging: any
  intl: any
  polymer_autonotify: 1.0.0-rc.10
  observe:
    git:
      ref: reflectable
      url: https://github.com/dam0vm3nt/observe.git

transformers:
- polymer_autonotify
- observe
- polymer:
    entry_points:
      - web/index.html
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
