name: remember_me
version: 0.0.1
description: A Polymer Dart application.

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.8
  logging: any
  intl: any
  autonotify_observe: ^1.0.0+7

transformers:
- autonotify_observe:
    entry_points:
    - web/index.html
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
