name: remember_me
description: A Polymer Dart application.
dependencies:
  core_elements: any
  paper_elements: any
  polymer: any
  intl: any
transformers:
- polymer:
    entry_points: web/index.html
- $dart2js:
    checked: false
    minify: true
    commandLineOptions: ['--trust-type-annotations', '--trust-primitives']