name: remember_me
description: A Polymer Dart application.

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.3
  polymer: ^1.0.0-rc.8
  web_components: ^0.12.0
  logging: any
  intl: any
  polymer_autonotify: 1.0.0-rc.8
  observe:
    git:
      ref: reflectable
      url: https://github.com/dam0vm3nt/observe.git

dependency_overrides:
  reflectable: 0.4.0

transformers:
- web_components:
    entry_points: web/index.html
- polymer_autonotify
- observe
- reflectable:
    entry_points: web/index.bootstrap.initialize.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
